# install all with:
# conda env create -f environment.yml
name: proteoclock
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python>=3.11
  - pip>=21.0
  - numpy>=2.0
  - pandas>=2.2
  - scipy>=1.7.0
  - matplotlib>=3.9
  - seaborn>=0.13
  - plotly>=6.0
  - scikit-learn>=1.5
  - pytorch>=2.0
  - pytorch-cuda=12.4
  - pip:
    - scikit_posthocs==0.11